namespace TarteelMobile.Services;

public partial class LocalVerseRepository
{
    private static readonly IReadOnlyList<JuzSeed> BuiltInJuzData =
    [
        new(1, 1, 1, 2, 141),
        new(2, 2, 142, 2, 252),
        new(3, 2, 253, 3, 92),
        new(4, 3, 93, 4, 23),
        new(5, 4, 24, 4, 147),
        new(6, 4, 148, 5, 81),
        new(7, 5, 82, 6, 110),
        new(8, 6, 111, 7, 87),
        new(9, 7, 88, 8, 40),
        new(10, 8, 41, 9, 92),
        new(11, 9, 93, 11, 5),
        new(12, 11, 6, 12, 52),
        new(13, 12, 53, 14, 52),
        new(14, 15, 1, 16, 128),
        new(15, 17, 1, 18, 110),
        new(16, 18, 111, 20, 135),
        new(17, 21, 1, 22, 78),
        new(18, 23, 1, 25, 20),
        new(19, 25, 21, 27, 55),
        new(20, 27, 56, 29, 45),
        new(21, 29, 46, 33, 30),
        new(22, 33, 31, 36, 27),
        new(23, 36, 28, 39, 31),
        new(24, 39, 32, 41, 46),
        new(25, 41, 47, 45, 37),
        new(26, 46, 1, 51, 30),
        new(27, 51, 31, 57, 29),
        new(28, 58, 1, 66, 12),
        new(29, 67, 1, 77, 50),
        new(30, 78, 1, 114, 6),
    ];

    private static readonly IReadOnlyList<SurahSeed> BuiltInSurahData =
    [
        new(1, "الفاتحة", "Al-Fatiha", "The Opening", "Meccan", 7),
        new(2, "البقرة", "Al-Baqarah", "The Cow", "Medinan", 286),
        new(3, "آل عمران", "Aal-E-Imran", "The Family of Imran", "Medinan", 200),
        new(4, "النساء", "An-Nisa", "The Women", "Medinan", 176),
        new(5, "المائدة", "Al-Ma'idah", "The Table Spread", "Medinan", 120),
        new(6, "الأنعام", "Al-An'am", "The Cattle", "Meccan", 165),
        new(7, "الأعراف", "Al-A'raf", "The Heights", "Meccan", 206),
        new(8, "الأنفال", "Al-Anfal", "The Spoils of War", "Medinan", 75),
        new(9, "التوبة", "At-Tawbah", "The Repentance", "Medinan", 129),
        new(10, "يونس", "Yunus", "Jonah", "Meccan", 109),
        new(11, "هود", "Hud", "Hud", "Meccan", 123),
        new(12, "يوسف", "Yusuf", "Joseph", "Meccan", 111),
        new(13, "الرعد", "Ar-Ra'd", "The Thunder", "Medinan", 43),
        new(14, "ابراهيم", "Ibrahim", "Abraham", "Meccan", 52),
        new(15, "الحجر", "Al-Hijr", "The Rocky Tract", "Meccan", 99),
        new(16, "النحل", "An-Nahl", "The Bee", "Meccan", 128),
        new(17, "الإسراء", "Al-Isra", "The Night Journey", "Meccan", 111),
        new(18, "الكهف", "Al-Kahf", "The Cave", "Meccan", 110),
        new(19, "مريم", "Maryam", "Mary", "Meccan", 98),
        new(20, "طه", "Ta-Ha", "Ta-Ha", "Meccan", 135),
        new(21, "الأنبياء", "Al-Anbiya", "The Prophets", "Meccan", 112),
        new(22, "الحج", "Al-Hajj", "The Pilgrimage", "Medinan", 78),
        new(23, "المؤمنون", "Al-Mu'minun", "The Believers", "Meccan", 118),
        new(24, "النور", "An-Nur", "The Light", "Medinan", 64),
        new(25, "الفرقان", "Al-Furqan", "The Criterion", "Meccan", 77),
        new(26, "الشعراء", "Ash-Shu'ara", "The Poets", "Meccan", 227),
        new(27, "النمل", "An-Naml", "The Ant", "Meccan", 93),
        new(28, "القصص", "Al-Qasas", "The Stories", "Meccan", 88),
        new(29, "العنكبوت", "Al-Ankabut", "The Spider", "Meccan", 69),
        new(30, "الروم", "Ar-Rum", "The Romans", "Meccan", 60),
        new(31, "لقمان", "Luqman", "Luqman", "Meccan", 34),
        new(32, "السجدة", "As-Sajdah", "The Prostration", "Meccan", 30),
        new(33, "الأحزاب", "Al-Ahzab", "The Combined Forces", "Medinan", 73),
        new(34, "سبأ", "Saba", "Sheba", "Meccan", 54),
        new(35, "فاطر", "Fatir", "Originator", "Meccan", 45),
        new(36, "يس", "Ya-Sin", "Ya Sin", "Meccan", 83),
        new(37, "الصافات", "As-Saffat", "Those Who Set The Ranks", "Meccan", 182),
        new(38, "ص", "Sad", "The Letter Sad", "Meccan", 88),
        new(39, "الزمر", "Az-Zumar", "The Troops", "Meccan", 75),
        new(40, "غافر", "Ghafir", "The Forgiver", "Meccan", 85),
        new(41, "فصلت", "Fussilat", "Explained in Detail", "Meccan", 54),
        new(42, "الشورى", "Ash-Shura", "The Consultation", "Meccan", 53),
        new(43, "الزخرف", "Az-Zukhruf", "The Ornaments of Gold", "Meccan", 89),
        new(44, "الدخان", "Ad-Dukhan", "The Smoke", "Meccan", 59),
        new(45, "الجاثية", "Al-Jathiyah", "The Crouching", "Meccan", 37),
        new(46, "الأحقاف", "Al-Ahqaf", "The Wind-Curved Sandhills", "Meccan", 35),
        new(47, "محمد", "Muhammad", "Muhammad", "Medinan", 38),
        new(48, "الفتح", "Al-Fath", "The Victory", "Medinan", 29),
        new(49, "الحجرات", "Al-Hujurat", "The Rooms", "Medinan", 18),
        new(50, "ق", "Qaf", "The Letter Qaf", "Meccan", 45),
        new(51, "الذاريات", "Adh-Dhariyat", "The Winnowing Winds", "Meccan", 60),
        new(52, "الطور", "At-Tur", "The Mount", "Meccan", 49),
        new(53, "النجم", "An-Najm", "The Star", "Meccan", 62),
        new(54, "القمر", "Al-Qamar", "The Moon", "Meccan", 55),
        new(55, "الرحمن", "Ar-Rahman", "The Beneficent", "Medinan", 78),
        new(56, "الواقعة", "Al-Waqi'ah", "The Inevitable", "Meccan", 96),
        new(57, "الحديد", "Al-Hadid", "The Iron", "Medinan", 29),
        new(58, "المجادلة", "Al-Mujadila", "The Pleading Woman", "Medinan", 22),
        new(59, "الحشر", "Al-Hashr", "The Exile", "Medinan", 24),
        new(60, "الممتحنة", "Al-Mumtahanah", "She That Is To Be Examined", "Medinan", 13),
        new(61, "الصف", "As-Saff", "The Ranks", "Medinan", 14),
        new(62, "الجمعة", "Al-Jumu'ah", "The Congregation, Friday", "Medinan", 11),
        new(63, "المنافقون", "Al-Munafiqun", "The Hypocrites", "Medinan", 11),
        new(64, "التغابن", "At-Taghabun", "The Mutual Disillusion", "Medinan", 18),
        new(65, "الطلاق", "At-Talaq", "The Divorce", "Medinan", 12),
        new(66, "التحريم", "At-Tahrim", "The Prohibition", "Medinan", 12),
        new(67, "الملك", "Al-Mulk", "The Sovereignty", "Meccan", 30),
        new(68, "القلم", "Al-Qalam", "The Pen", "Meccan", 52),
        new(69, "الحاقة", "Al-Haqqah", "The Reality", "Meccan", 52),
        new(70, "المعارج", "Al-Ma'arij", "The Ascending Stairways", "Meccan", 44),
        new(71, "نوح", "Nuh", "Noah", "Meccan", 28),
        new(72, "الجن", "Al-Jinn", "The Jinn", "Meccan", 28),
        new(73, "المزمل", "Al-Muzzammil", "The Enshrouded One", "Meccan", 20),
        new(74, "المدثر", "Al-Muddaththir", "The Cloaked One", "Meccan", 56),
        new(75, "القيامة", "Al-Qiyamah", "The Resurrection", "Meccan", 40),
        new(76, "الانسان", "Al-Insan", "The Man", "Medinan", 31),
        new(77, "المرسلات", "Al-Mursalat", "The Emissaries", "Meccan", 50),
        new(78, "النبأ", "An-Naba", "The Tidings", "Meccan", 40),
        new(79, "النازعات", "An-Nazi'at", "Those Who Drag Forth", "Meccan", 46),
        new(80, "عبس", "Abasa", "He Frowned", "Meccan", 42),
        new(81, "التكوير", "At-Takwir", "The Overthrowing", "Meccan", 29),
        new(82, "الإنفطار", "Al-Infitar", "The Cleaving", "Meccan", 19),
        new(83, "المطففين", "Al-Mutaffifin", "The Defrauding", "Meccan", 36),
        new(84, "الإنشقاق", "Al-Inshiqaq", "The Sundering", "Meccan", 25),
        new(85, "البروج", "Al-Buruj", "The Mansions of the Stars", "Meccan", 22),
        new(86, "الطارق", "At-Tariq", "The Morning Star", "Meccan", 17),
        new(87, "الأعلى", "Al-A'la", "The Most High", "Meccan", 19),
        new(88, "الغاشية", "Al-Ghashiyah", "The Overwhelming", "Meccan", 26),
        new(89, "الفجر", "Al-Fajr", "The Dawn", "Meccan", 30),
        new(90, "البلد", "Al-Balad", "The City", "Meccan", 20),
        new(91, "الشمس", "Ash-Shams", "The Sun", "Meccan", 15),
        new(92, "الليل", "Al-Layl", "The Night", "Meccan", 21),
        new(93, "الضحى", "Ad-Duha", "The Morning Hours", "Meccan", 11),
        new(94, "الشرح", "Ash-Sharh", "The Relief", "Meccan", 8),
        new(95, "التين", "At-Tin", "The Fig", "Meccan", 8),
        new(96, "العلق", "Al-Alaq", "The Clot", "Meccan", 19),
        new(97, "القدر", "Al-Qadr", "The Power", "Meccan", 5),
        new(98, "البينة", "Al-Bayyinah", "The Clear Proof", "Medinan", 8),
        new(99, "الزلزلة", "Az-Zalzalah", "The Earthquake", "Medinan", 8),
        new(100, "العاديات", "Al-Adiyat", "The Courser", "Meccan", 11),
        new(101, "القارعة", "Al-Qari'ah", "The Calamity", "Meccan", 11),
        new(102, "التكاثر", "At-Takathur", "The Rivalry in World Increase", "Meccan", 8),
        new(103, "العصر", "Al-Asr", "The Declining Day", "Meccan", 3),
        new(104, "الهمزة", "Al-Humazah", "The Traducer", "Meccan", 9),
        new(105, "الفيل", "Al-Fil", "The Elephant", "Meccan", 5),
        new(106, "قريش", "Quraysh", "Quraysh", "Meccan", 4),
        new(107, "الماعون", "Al-Ma'un", "The Small Kindnesses", "Meccan", 7),
        new(108, "الكوثر", "Al-Kawthar", "The Abundance", "Meccan", 3),
        new(109, "الكافرون", "Al-Kafirun", "The Disbelievers", "Meccan", 6),
        new(110, "النصر", "An-Nasr", "The Divine Support", "Medinan", 3),
        new(111, "المسد", "Al-Masad", "The Palm Fiber", "Meccan", 5),
        new(112, "الإخلاص", "Al-Ikhlas", "The Sincerity", "Meccan", 4),
        new(113, "الفلق", "Al-Falaq", "The Daybreak", "Meccan", 5),
        new(114, "الناس", "An-Nas", "Mankind", "Meccan", 6),
    ];

    private sealed record JuzSeed(int JuzNum, int StartSurah, int StartAyah, int EndSurah, int EndAyah);
    private sealed record SurahSeed(int SurahNum, string NameArabic, string NameEnglish, string NameTransliteration, string RevelationType, int AyahCount);
}
