<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="*" />
  </ItemGroup>

</Project>
